# Generated by Django 5.2.5 on 2026-10-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hazard', models.CharField(choices=[('malaria', 'Malaria'), ('heat', 'Heat'), ('flood', 'Flood')], max_length=10)),
                ('score', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very high')], max_length=10)),
                ('explanation', models.TextField(help_text='Plain-language reason: every alert says why')),
                ('inputs', models.JSONField(default=dict)),
                ('source', models.CharField(default='open-meteo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.lga')),
            ],
            options={
                'ordering': ['-date', 'hazard'],
                'unique_together': {('lga', 'date', 'hazard')},
            },
        ),
        migrations.CreateModel(
            name='WeatherDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('apparent_temp_max', models.FloatField()),
                ('precipitation_mm', models.FloatField()),
                ('humidity_mean', models.FloatField()),
                ('is_forecast', models.BooleanField(default=False)),
                ('source', models.CharField(default='open-meteo', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='core.lga')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('lga', 'date')},
            },
        ),
    ]
