# Generated by Django 5.2.5 on 2026-10-08 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'LGA',
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('phc', 'Primary Health Centre'), ('chc', 'Comprehensive Health Centre'), ('gh', 'General Hospital'), ('th', 'Teaching Hospital')], default='phc', max_length=5)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('services', models.CharField(help_text='Comma-separated service codes, e.g. immunization,antenatal', max_length=200)),
                ('open_days', models.CharField(default='01234', help_text='Weekday digits, Monday=0', max_length=7)),
                ('opens_at', models.TimeField(default='08:00')),
                ('closes_at', models.TimeField(default='16:00')),
                ('is_24h', models.BooleanField(default=False)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.lga')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('pcm', 'Nigerian Pidgin')], default='en', max_length=3)),
                ('role', models.CharField(choices=[('family', 'Family / individual'), ('worker', 'Health worker'), ('government', 'Government / partner')], default='family', max_length=12)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('facility', models.ForeignKey(blank=True, help_text='Health workers: facility of work', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.lga')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.profile')),
            ],
            options={
                'verbose_name_plural': 'children',
                'ordering': ['date_of_birth'],
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='core.state'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.lga')),
            ],
            options={
                'ordering': ['lga__name', 'name'],
                'unique_together': {('lga', 'name')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward'),
        ),
        migrations.AddField(
            model_name='facility',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='lga',
            unique_together={('state', 'name')},
        ),
    ]
