# Generated by Django 5.2.5 on 2026-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Synthetic/demo data — excluded from validation evidence'),
        ),
    ]
