# Generated by Django 5.2.5 on 2026-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='area_sqkm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lga',
            name='pcode',
            field=models.CharField(blank=True, help_text='OCHA COD-AB code', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='state',
            name='pcode',
            field=models.CharField(blank=True, help_text='OCHA COD-AB code', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(help_text='ISO 3166-2:NG code, e.g. LA', max_length=5, unique=True),
        ),
    ]
