# Generated by Django 5.2.5 on 2026-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lga_area_sqkm_lga_pcode_state_pcode_alter_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='external_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='functional',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='facility',
            name='hours_verified',
            field=models.BooleanField(default=True, help_text='False = typical hours and likely services inferred from facility type'),
        ),
        migrations.AddField(
            model_name='facility',
            name='level',
            field=models.CharField(blank=True, help_text='Primary / Secondary / Tertiary', max_length=10),
        ),
        migrations.AddField(
            model_name='facility',
            name='ownership',
            field=models.CharField(blank=True, help_text='Public / Private', max_length=10),
        ),
        migrations.AddField(
            model_name='facility',
            name='registry_code',
            field=models.CharField(blank=True, help_text='Nigeria Health Facility Registry code', max_length=40),
        ),
        migrations.AddField(
            model_name='facility',
            name='source',
            field=models.CharField(default='manual', help_text='GRID3 v3.0 / GRID3 v2.0 / demo / manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('phc', 'Primary Health Centre'), ('hp', 'Health Post'), ('clin', 'Clinic'), ('mat', 'Maternity Home'), ('chc', 'Comprehensive Health Centre'), ('hosp', 'Hospital'), ('gh', 'General Hospital'), ('th', 'Teaching / Tertiary Hospital'), ('oth', 'Other')], default='phc', max_length=5),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['latitude', 'longitude'], name='core_facili_latitud_9e1900_idx'),
        ),
    ]
