# Generated by Django 5.2.5 on 2026-10-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('protects_against', models.CharField(max_length=150)),
                ('age_days', models.PositiveIntegerField(help_text='Recommended age in days on the routine schedule')),
                ('age_label', models.CharField(max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['age_days', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='core.child')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunitrack.vaccine')),
            ],
            options={
                'ordering': ['given_date'],
                'unique_together': {('child', 'vaccine')},
            },
        ),
    ]
