# Generated by Django 5.2.5 on 2026-10-08 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('malaria', 'Malaria risk'), ('heat', 'Heat risk'), ('flood', 'Flood risk'), ('vaccine', 'Vaccine reminder'), ('anc', 'Antenatal reminder'), ('reminder', 'Booked reminder')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('pcm', 'Nigerian Pidgin')], default='en', max_length=3)),
                ('reason', models.TextField(blank=True, help_text='Why this alert was sent (explainable risk)')),
                ('scheduled_for', models.DateField(default=django.utils.timezone.localdate)),
                ('channel', models.CharField(default='app', max_length=10)),
                ('generated_by', models.CharField(default='template', help_text='n-atlas or template', max_length=10)),
                ('dedupe_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('acted_on_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.profile')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
                'unique_together': {('profile', 'dedupe_key')},
            },
        ),
    ]
