# Generated by Django 5.2.5 on 2026-10-08 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.profile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Lafiya')], max_length=10)),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('pcm', 'Nigerian Pidgin')], default='en', max_length=3)),
                ('intent', models.CharField(blank=True, max_length=20)),
                ('emergency', models.BooleanField(default=False)),
                ('generated_by', models.CharField(blank=True, max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='navigator.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('immunization', 'Immunization'), ('antenatal', 'Antenatal care'), ('delivery', 'Delivery'), ('malaria', 'Malaria testing & treatment'), ('ncd', 'BP & diabetes screening'), ('nutrition', 'Child nutrition'), ('emergency', 'Emergency care')], max_length=15)),
                ('reason', models.CharField(max_length=200)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Today'), ('emergency', 'Emergency')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted by user'), ('completed', 'Completed at facility'), ('cancelled', 'Cancelled')], default='suggested', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.facility')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
