# Generated by Django 5.2.5 on 2026-10-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_is_demo'),
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('web', 'Web app'), ('whatsapp', 'WhatsApp')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='asr_engine',
            field=models.CharField(blank=True, help_text='n-atlas or browser (voice input only)', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('web', 'Web app'), ('whatsapp', 'WhatsApp')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='input_mode',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=5),
        ),
        migrations.AddField(
            model_name='message',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='E.164, e.g. +2348012345678', max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('pcm', 'Nigerian Pidgin')], default='en', max_length=3)),
                ('state', models.CharField(choices=[('language', 'Choosing language'), ('consent', 'Awaiting consent'), ('location', 'Awaiting location'), ('ready', 'Ready')], default='language', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp', to='core.profile')),
            ],
        ),
    ]
