# Generated by Django 5.2.5 on 2026-10-08 15:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_conversation_channel_message_asr_engine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('pcm', 'Nigerian Pidgin')], default='en', max_length=3)),
                ('voice', models.CharField(blank=True, max_length=80)),
                ('audio', models.BinaryField()),
                ('content_type', models.CharField(default='audio/mpeg', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_clips', to='navigator.message')),
            ],
        ),
    ]
