# Generated by Django 5.2.5 on 2026-10-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pregnancy', 'Pregnancy'), ('newborn', 'Newborn (0–28 days)'), ('child', 'Child under 5')], max_length=10)),
                ('sign', models.CharField(max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated, used by the Care Navigator', max_length=250)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.PositiveSmallIntegerField()),
                ('domain', models.CharField(choices=[('motor', 'Movement'), ('social', 'Social & emotional'), ('language', 'Language'), ('cognitive', 'Learning'), ('care', 'Care & feeding')], max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['age_months', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmp_date', models.DateField(verbose_name='first day of last menstrual period')),
                ('edd', models.DateField(blank=True, verbose_name='expected date of delivery')),
                ('active', models.BooleanField(default=True)),
                ('high_risk', models.BooleanField(default=False, help_text='Flagged by a health worker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='core.profile')),
            ],
            options={
                'verbose_name_plural': 'pregnancies',
                'ordering': ['-lmp_date'],
            },
        ),
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.PositiveSmallIntegerField()),
                ('gestation_week', models.PositiveSmallIntegerField()),
                ('scheduled_date', models.DateField()),
                ('attended_date', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='mamacare.pregnancy')),
            ],
            options={
                'verbose_name': 'ANC visit',
                'ordering': ['contact_number'],
                'unique_together': {('pregnancy', 'contact_number')},
            },
        ),
    ]
